config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, path: '' do
    get '/sign_out' => 'devise/sessions#destroy'
  end
  resources :recipes, except: [:update] do
    resources :recipe_foods
  end
  resources :foods, except: [:update]
  resources :recipe_foods
  resources :users, only: %i[index show create destroy]
  get 'shopping_list', to: 'shopping_list#index'
  resources :public_recipes

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'users#index'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods

  validates :name, presence: true
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.all
    @public_recipes = @recipes.where(public: true)
    @private_recipes = @recipes.where(user: current_user)
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @recipe = Recipe.find(params[:id])
    @food = Food.all
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit; end

  # POST /recipes or /recipes.json
  def create
    @user = current_user
    @recipe = Recipe.new(recipe_params)
    @recipe.user = @user

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def add_ingredient
    @food = Food.find(params[:id]).name
    @quantity = Food.find(params[:id]).quantity
    RecipeFood.create!(food: @food, quantity: @quantity)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :preparation_time, style: "display: block" %>
    <%= form.number_field :preparation_time %>
  </div>

  <div>
    <%= form.label :cooking_time, style: "display: block" %>
    <%= form.number_field :cooking_time %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :public, style: "display: block" %>
    <%= form.check_box :public %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div class="recipe__content" id="<%= dom_id recipe %>">
  <p class="recipe__content__name">
    <strong>Name:</strong>
    <%= recipe.name %>
  </p>

  <p class="recipe__content__prep">
    <strong>Preparation time:</strong>
    <%= recipe.preparation_time %>
  </p>

  <p class="recipe__content__cook">
    <strong>Cooking time:</strong>
    <%= recipe.cooking_time %>
  </p>

  <p class="recipe__content__description">
    <strong>Description:</strong>
    <%= recipe.description %>
  </p>

  <p class="recipe__content__public">
    <strong>Public:</strong>

    <%= recipe.public %>
  </p>

</div>
<hr>
<%=link_to 'Add Ingredient', new_recipe_recipe_food_path(@recipe)%>

app/views/recipes/_recipe_list.html.erb
<%= link_to recipe_path(recipe.id), :action => 'go' do%>
<div class="recipe__content">
  <p class="recipe__content__name">
    <strong>Name:</strong>
    <%= recipe.name %>
  </p>
  <p class="recipe__content__description">
    <strong>Description:</strong>
    <%= recipe.description %>
  </p>
  <%end%>
<%if recipe.user_id == current_user.id %>
  <%= button_to "Delete this recipe", {:controller => :recipes, :action => 'destroy', :id => recipe.id}, method: :delete %>
<%else%>
<%= link_to recipe_path(recipe.id), :action => 'go'%>
<%end%>
</div>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="title">Recipes</h1>

<div id="recipes">
<%if @private_recipes.empty?%>
  <h2 class="recipes__null">No recipes</h2>
<%else%>
  <% @private_recipes.each do |recipe| %>
    <%= render 'recipe_list', recipe: %>
  <% end %>
<%end%>
</div>

<%= link_to "New recipe", new_recipe_path, class:'new_recipe' %>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/show.html.erb
<p style="color: green"><%= notice %></p>
<%# Shopping list %>
 <%= link_to "Generate shopping list", shopping_list_path, class: 'btn-primary' %>
<%= render @recipe %>

<div>
  <%= link_to "Edit this recipe", edit_recipe_path(@recipe) %> |
  <%= link_to "Back to recipes", :back %>

  <%= button_to "Destroy this recipe", @recipe, method: :delete %>
</div>