config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, path: '' do
    get '/sign_out' => 'devise/sessions#destroy'
  end
  resources :recipes, except: [:update] do
    resources :recipe_foods
  end
  resources :foods, except: [:update]
  resources :recipe_foods
  resources :users, only: %i[index show create destroy]
  get 'shopping_list', to: 'shopping_list#index'
  resources :public_recipes

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'users#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Receipe App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
  <div class="center">
  <p class="notice">  <%= notice %> </p>
  <p class="alert"> <%= alert %> </p>
  <header class='header'>
    <nav class='header__nav'>
      <ul class='header__nav_list'>
        <li class='header__nav_list__element'><%= image_tag 'logo.png',class:'header__nav_list__img'%></li>
        <%=link_to users_path(), action: 'go' do%>
        <li class='header__nav_list__element'>Home</li>
        <%end%>
        <%=link_to recipes_path(), action: 'go' do%>
        <li class='header__nav_list__element'>My Recipes</li>
        <%end%>
        <%=link_to public_recipes_path(), action: 'go' do%>
        <li class='header__nav_list__element'>Public Recipes</li>
        <%end%>
        <%=link_to foods_path(), action:'go' do%>
        <li class='header__nav_list__element'>Food</li>
        <%end%>
        <%=link_to shopping_list_path(), action:'go' do %>
        <li class='header__nav_list__element'>Shipping List</li>
        <%end%>
      </ul>
    </nav>
  </header>

    <%= yield %>
    </div>
  </body>
</html>